name: Haskell CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  on-main-update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-haskell@v2.6.2
      with:
        ghc-version: '9.6.3'
        cabal-version: '3.10.2.1'

    - name: Cache
      uses: actions/cache@v4.0.1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Build package
      run:
      	cabal update
        cabal new-build all

    - name: Upload package
      env:
      	HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
      run:
        cabal sdist
        cabal upload --username=VladimirSinyakov --password="$HACKAGE_PASSWORD" dist-newstyle/sdist/*.tar.gz
        
        cabal v2-haddock --haddock-for-hackage --enable-doc
        cabal upload --documentation --username=VladimirSinyakov --password="$HACKAGE_PASSWORD" dist-newstyle/*-docs.tar.gz
